name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that we are in sync with M2 repo
        run: |
          mkdir tmp
          wget -P tmp https://raw.githubusercontent.com/Macaulay2/M2/refs/heads/development/M2/Macaulay2/packages/TerraciniLoci.m2
          diff -us TerraciniLoci.m2 tmp/TerraciniLoci.m2
      - name: Install Macaulay2
        run: |
          sudo add-apt-repository ppa:macaulay2/macaulay2
          sudo apt-get install -y --no-install-recommends macaulay2
      - name: Install TerraciniLoci package
        run: M2 -q --stop -e 'installPackage "TerraciniLoci"; exit 0'
      - name: Test TerraciniLoci package
        run: M2 -q --stop -e 'check needsPackage "TerraciniLoci"; exit 0'
