name: test
on:
  push:
    branches: 'master'
  schedule:
    - cron: '0 12 15 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check that we are in sync with M2 repo
        run: |
          mkdir tmp
          wget -P tmp https://raw.githubusercontent.com/Macaulay2/M2/refs/heads/development/M2/Macaulay2/packages/TerraciniLoci.m2
          diff -us TerraciniLoci.m2 tmp/TerraciniLoci.m2
      - name: Install Macaulay2
        run: |
          sudo add-apt-repository ppa:macaulay2/macaulay2
          sudo apt-get install -y --no-install-recommends macaulay2
      - name: Install TerraciniLoci package
        run: M2 -q --stop -e 'installPackage "TerraciniLoci"; exit 0'
      - name: Test TerraciniLoci package
        run: M2 -q --stop -e 'check needsPackage "TerraciniLoci"; exit 0'
      - name: Build documentation site
        run: |
          mkdir site
          cp -rL ~/.Macaulay2/local/share/doc/Macaulay2/TerraciniLoci/html/. site
          cp -rL /usr/share/Macaulay2/Style site/Style
          sed -i \
            -e 's,/usr/share/Macaulay2/Style,Style,g' \
            -e 's,/usr/share/doc/Macaulay2,https://www.macaulay2.com/doc/Macaulay2/share/doc/Macaulay2,g' \
            site/*.html
          touch site/.nojekyll
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
